### PR TITLE
Nuxt integration

### PR DESCRIPTION
**Pull request by alexgrozav**

### CODE REVIEW

**Comment by liamcharmer** [comment]
Whenever I install and then try to put the module part, says cannot find module?

**Comment by alexgrozav** [comment]
@liamcharmer can you try updating to @inkline/inkline@1.15.3? I forgot to include the `nuxt` folder into the released npm package.

**Comment by liamcharmer** [comment]
@alexgrozav Works perfect! Apologies!!! Thank you very much! Saw the tweet and really wanted to get into it and give it a try! Thanks for the hard work!

**Comment by alexgrozav** [comment]
I'm so glad to hear that! I'd love to hear your feedback when you find the time.

**Comment by alexgrozav** [comment]
There might have been an issue in `1.15.3` due to how the latest version of webpack is loading node_modules packages in the Vue SSR. Make sure to update to `1.15.4` to fix it. Sorry for the inconvenience!

**Pull request merged**
